name: generate pacman game

on:
  schedule:
    - cron: "0 */24 * * *"   # 1 fois / 24h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph
        with:
          github_user_name: ${{ github.repository_owner }}
          # options possibles :
          # gameTheme: github-dark
          # output: svg

      # Publie les fichiers générés (dans /dist) vers la branche "output"
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
