# .github/workflows/pacman.yml
name: GitHub Pac-Man

on:
  schedule:
    - cron: "0 */12 * * *"   # toutes les 12h
  workflow_dispatch:

permissions:
  contents: write   # nécessaire pour committer le SVG généré

jobs:
  pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Generate Pac-Man graph
        uses: abozanona/pacman-contribution-graph@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # options possibles (facultatif) :
          # username: Thomasrbm
          # output_path: output/github-contribution-grid-pacman.svg
          # theme: dark
