jobs:
  pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: GitHub Pac-Man
        uses: abozanona/pacman-contribution-graph@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
